Improve Build / Cleanup README
epics-extensions/ezca pull request #1
Opened 2021-06-02 10:14 UTC by simongregorebner

Improve the build by adding a default `configure` directory (similar to whats in https://github.com/epics-extensions/ca-gateway)

Cleanup of the README

2021-06-02 17:53 UTC, anjohnson commented
Hi Simon,

In principle I'm fine with this, thanks for submitting it. However could you please move the source files and their Makefile which builds everything into a `src/` subdirectory. The new top-level Makefile should then include our standard `configure/RULES_TOP` which you can find in `Base/templates/makeBaseApp/top/configure` – ezca doesn't need the extra emtop stuff which I assume you just copied from the gateway's `configure/RULES_TOP` file.

Thanks,

- Andrew

2021-08-17 09:03 UTC, simongregorebner commented
Using now the default `Base/templates/makeBaseApp/top/configure` from Epics base.

2021-08-20 15:02 UTC, MarkRivers commented
Is the plan that all extensions will switch to this new packaging, and the extensions/configure directory will no longer be used?  I seem to be the maintainer for ezcaIDL and EzcaScan so should I be doing this?

2021-08-23 15:52 UTC, anjohnson commented
Hi Mark,

> Is the plan that all extensions will switch to this new packaging, and the extensions/configure directory will no longer be used?

I think that's probably the best course of action. Different sets of tools can still be installed into a common `bin/<arch>` directory after conversion by setting `INSTALL_LOCATION` in their `configure/CONFIG_SITE` file.

The original extensions tree was designed for X11 and Motif applications but it doesn't really work for building programs that use newer toolkits like Qt, so more recent tools haven't been using it at all. I would like to drop support for the extensions configure area which combines many different sets of build rules, but I don't have time to help converting the existing tools myself.

Thanks,

- Andrew

2021-08-23 16:04 UTC, anjohnson requested changes
It looks like Simon moved the source files back out of the new `src/` directory again in commit 6bd7614de23bee69014d0bb754cf3faa3c7c1741 instead of creating a new Makefile in that directory to do the actual build. I don't like the current file structure, it just needs a bit more work after that commit to get it to build properly — I'd be happy to answer questions about what needs doing.

2025-09-17 14:31 UTC, closed without merging